# Generated by Django 5.2.6 on 2025-09-15 04:15

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSMLocationCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('osm_id', models.BigIntegerField(help_text='OpenStreetMap node/way/relation ID', unique=True)),
                ('osm_type', models.CharField(choices=[('node', 'Node'), ('way', 'Way'), ('relation', 'Relation')], default='node', help_text='Type of OSM element (node, way, relation)', max_length=10)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Latitude in decimal degrees', max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitude in decimal degrees', max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('name', models.CharField(blank=True, help_text='Name of the location/business', max_length=255, null=True)),
                ('amenity_type', models.CharField(choices=[('fuel', 'Fuel Station'), ('truck_stop', 'Truck Stop'), ('gas_station', 'Gas Station'), ('charging_station', 'EV Charging Station'), ('rest_area', 'Rest Area'), ('service_area', 'Service Area'), ('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('hotel', 'Hotel'), ('parking', 'Parking'), ('toilets', 'Toilets'), ('atm', 'ATM'), ('shop', 'Shop/Convenience Store')], help_text='Type of amenity (fuel, truck_stop, etc.)', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Full address if available from OSM', null=True)),
                ('city', models.CharField(blank=True, help_text='City name', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State/province', max_length=50, null=True)),
                ('country', models.CharField(blank=True, help_text='Country', max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20, null=True)),
                ('fuel_types', models.JSONField(blank=True, default=list, help_text='Available fuel types (diesel, gasoline, etc.)')),
                ('truck_accessible', models.BooleanField(default=False, help_text='Whether trucks can access this location')),
                ('hgv_parking', models.BooleanField(default=False, help_text='Has parking for Heavy Goods Vehicles')),
                ('has_restaurant', models.BooleanField(default=False)),
                ('has_toilets', models.BooleanField(default=False)),
                ('has_atm', models.BooleanField(default=False)),
                ('has_shop', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_shower', models.BooleanField(default=False)),
                ('opening_hours', models.CharField(blank=True, help_text='Opening hours in OSM format', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=50, null=True)),
                ('website', models.URLField(blank=True, help_text='Website URL', null=True)),
                ('brand', models.CharField(blank=True, help_text='Brand name (Shell, BP, Pilot, etc.)', max_length=100, null=True)),
                ('operator', models.CharField(blank=True, help_text='Operator/company name', max_length=100, null=True)),
                ('cache_status', models.CharField(choices=[('active', 'Active'), ('stale', 'Stale (needs refresh)'), ('invalid', 'Invalid (OSM data changed)'), ('archived', 'Archived')], default='active', help_text='Status of this cached location', max_length=20)),
                ('raw_osm_data', models.JSONField(blank=True, help_text='Raw OSM tags for reference', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('osm_last_modified', models.DateTimeField(blank=True, help_text='Last modified date from OSM', null=True)),
                ('cache_expires_at', models.DateTimeField(help_text='When this cache entry expires and needs refresh')),
            ],
            options={
                'verbose_name': 'OSM Location Cache',
                'verbose_name_plural': 'OSM Location Cache',
                'db_table': 'routes_osm_location_cache',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='routes_osm__latitud_ffe8c8_idx'), models.Index(fields=['amenity_type'], name='routes_osm__amenity_a2f7b9_idx'), models.Index(fields=['truck_accessible'], name='routes_osm__truck_a_5a5442_idx'), models.Index(fields=['cache_status'], name='routes_osm__cache_s_f48ebf_idx'), models.Index(fields=['cache_expires_at'], name='routes_osm__cache_e_fb6bc3_idx'), models.Index(fields=['city', 'state'], name='routes_osm__city_374222_idx'), models.Index(fields=['brand'], name='routes_osm__brand_9357d0_idx')],
            },
        ),
    ]
