# Generated by Django 5.2.6 on 2025-09-14 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos_compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosstatus',
            name='available_cycle_hours',
            field=models.DecimalField(decimal_places=1, default=70, help_text='Available hours remaining in 8-day cycle', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)]),
        ),
        migrations.AlterField(
            model_name='hosstatus',
            name='current_cycle_hours',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Current hours used in 8-day cycle (max 70)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)]),
        ),
    ]
